// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpcl1AK2aDuDw6ILq1dhFt9W0JvsLlRo8',
    appId: '1:217280421579:web:3562cfe19f7952ba15054e',
    messagingSenderId: '217280421579',
    projectId: 'alulaunchpad1-5b8fe',
    authDomain: 'alulaunchpad1-5b8fe.firebaseapp.com',
    databaseURL: 'https://alulaunchpad1-5b8fe-default-rtdb.firebaseio.com',
    storageBucket: 'alulaunchpad1-5b8fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNxcTh9K1BWpNg90z-g7ASn4c2INBboE',
    appId: '1:217280421579:android:4f73dde7ea46f13a15054e',
    messagingSenderId: '217280421579',
    projectId: 'alulaunchpad1-5b8fe',
    databaseURL: 'https://alulaunchpad1-5b8fe-default-rtdb.firebaseio.com',
    storageBucket: 'alulaunchpad1-5b8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0oZkdS3NV9QCrXqpdZPb8BowCZTvY_Vo',
    appId: '1:217280421579:ios:651a681a74b1e72515054e',
    messagingSenderId: '217280421579',
    projectId: 'alulaunchpad1-5b8fe',
    databaseURL: 'https://alulaunchpad1-5b8fe-default-rtdb.firebaseio.com',
    storageBucket: 'alulaunchpad1-5b8fe.firebasestorage.app',
    iosBundleId: 'com.example.aluLaunchpad',
  );
}
